on:
  issues:
    types: [labeled]
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.labels.*.name, 'accepted')
        name: Accept submission
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Your submission have been accepted
