on:
  issues:
    types: [labeled]
jobs:
  reviewSubmission:
    if: contains(github.event.issue.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.label.name == 'accepted' }}
        name: Accept submission
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Your submission have been accepted
      - if: ${{ github.event.label.name == 'refused' }}
        name: Refuse submission
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Your submission doesn't match our requirements

